# Generated by Django 5.0.7 on 2024-09-15 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default=datetime.datetime(2024, 9, 15, 16, 23, 37, 972845, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 9, 15, 16, 23, 41, 578655, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
