# Generated by Django 5.0.7 on 2024-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_student_faculty_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=1500)),
            ],
        ),
    ]
