# Generated by Django 5.0.7 on 2024-09-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='account_name',
            field=models.CharField(default=1, max_length=444),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='account_number',
            field=models.CharField(default=1, max_length=202),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='amount_withdraw',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='bank_code',
            field=models.CharField(default=1, max_length=202),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='bank_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
