# Generated by Django 5.0.7 on 2024-09-27 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_balance_account_name_balance_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 27, 18, 24, 57, 247484, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
