from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home, name='home'),
    path('make_payment/', make_payment, name='make_payment'),
    path('student_login/', student_login, name='student_login'),
    path('admin-dashboard/login/', admin_login, name='admin_login'),
    path('logout/', logout_view, name='logout'),
    path('check_payment/', check_payment, name='check_payment'),
    # path('make_payment/', make_payment, name='make_payment'),
    path('admin-dashboard/', admin_dashboard , name='admin_dashboard'),
    path('all-payments/', all_payments , name='all_payments'),
    path('withdrawals/', withdrawals , name='withdrawals'),
    path('api/banks/', get_banks , name='get_banks'),
    path('withdraw-cash/', withdraw_cash , name='withdraw_cash'),
    # path('make_payments/', make_payments, name='make_payments'),
     path('view-receipts/', view_receipts, name='view_receipts'),
    path('payment_receipt/<int:payment_id>/', payment_receipt, name='payment_receipt'),
    path('create-account/', signup, name='signup'),
    path('all-students/', view_all_students, name='all_students'),
    path('login/', login_view, name='login'),
    path('search_payments/', search_payments, name='search_payments'),
    path('search_withdrawal/', search_withdrawal, name='search_withdrawal'),
    path('department-fee/', department_fee, name='department_fee'),
    path('student-profile/', view_profile, name='student_profile'),
    path('search_students/', search_students, name='search_students'), 
    path('generate-report/', generate_report, name='generate_report'),
    path('generate-withdrawal-report/', generate_withdrawal_report, name='generate_withdrawal_report'),
    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name='reset_password.html', html_email_template_name = 'email_template.html'),
    name ='reset_password'),
    path('reset_password_sent/',
    auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'), 
    name ='password_reset_done'),
    path('reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(template_name='reset_password_confirm.html'),
    name ='password_reset_confirm'),
    path('reset_password_complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'),
    name ='password_reset_complete'),
]
